# Generated by Django 3.1.7 on 2021-02-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_jid', models.CharField(default='', max_length=255, unique=True)),
                ('callback_uri', models.CharField(default='', max_length=255)),
                ('callback_secret', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
